# Generated by Django 5.2.16 on 2026-07-28 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_driver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WPAY', 'Waiting For Payment'), ('PAID', 'Paid'), ('PREP', 'In Preparation'), ('SHPD', 'Shipped'), ('DLVD', 'Delivered')], max_length=30)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.driver')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx')],
            },
        ),
    ]
