# Generated by Django 5.2.16 on 2026-07-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('APAY', 'Awaiting payment'), ('PAID', 'Paid'), ('PREP', 'In Preparation'), ('SHPD', 'Shipped'), ('DLVD', 'Delivered')], default='APAY', max_length=30),
        ),
    ]
