# Generated by Django 5.2.16 on 2026-08-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('AWAITING PAYMENT', 'Awaiting payment'), ('PAID', 'Paid'), ('IN PREPRATION', 'In Preparation'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], default='AWAITING PAYMENT', max_length=30),
        ),
    ]
