# Generated by Django 5.2.16 on 2026-07-30 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orders_orde_created_0e92de_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='buyer',
            new_name='customer',
        ),
    ]
