# Generated by Django 5.2.16 on 2026-07-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_buyer_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WPAY', 'Waiting For Payment'), ('PAID', 'Paid'), ('PREP', 'In Preparation'), ('SHPD', 'Shipped'), ('DLVD', 'Delivered')], default='WPAY', max_length=30),
        ),
    ]
