# Generated by Django 5.2.16 on 2026-07-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketmessage_messageattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PEND', 'Pending'), ('CLSD', 'Closed')], default='OPEN', max_length=4),
        ),
    ]
