# Generated by Django 5.2.16 on 2026-08-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_messageattachment_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLSD', 'Closed')], default='OPEN', max_length=4),
        ),
    ]
